name: Calculate JS Bundle Size

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
jobs:
  calculate-size:
    steps:
      - uses: actions/checkout@master
      - uses: sarthak-saxena/JSBundleSize@master
        with:
          bootstrap: 'yarn install --ignore-engines'
          build_command: 'yarn run production'
          dist_path: '/dist'
          token: ${{ secrets.GITHUB_TOKEN }}